name: Send mail
on: push

jobs: 
  mail:
    runs-on: ubuntu-latest

    steps:
    - name: print hello world
      run: echo "Helolo world"

    - name: sending a mail
      if: $ {{ always() }}
      uses: devellany/send-mailer@v1.0.2
      with:
          host: smtp.google.com
          # Optional port (defaults to 465)
          port: 465
          account: ${{secrets.ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: jay
          from: ${{secrets.MAIL_ADDRESS}}
          to: mail2jay4data@gmail.com
          subject: Test mail
          body: Working fine
    
